package main

import (
	"log"
	"math/rand"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html/v2"
)

var messages = []string{
	"It is certain",
	"It is decidedly so",
	"Without a doubt",
	"Yes, definitely",
	"You may rely on it",
	"As I see it, yes",
	"Most likely",
	"Outlook good",
	"Yes",
	"Signs point to yes",
	"Reply hazy, try again",
	"Ask again later",
	"Better not tell you now",
	"Cannot predict now",
	"Concentrate and ask again",
	"Don't count on it",
	"My reply is no",
	"My sources say no",
	"Outlook not so good",
	"Very doubtful",
}

func main() {
	// Initialize standard Go html template engine
	engine := html.New("./views", ".tmpl")

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	app.Static("/public", "./public")

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("index", fiber.Map{
			"Title": "Magic 8 Ball",
		})
	})

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.SendString("OK")
	})

	app.Get("/shake", func(c *fiber.Ctx) error {
		// Ensure randomization works across requests.
		// math/rand is fine for this non-cryptographic use.
		message := messages[rand.Intn(len(messages))]

		// Requirement 10: The path it will follow and the number of times it hits the bumpers will be generated by the backend.
		// Requirement 9: Hit the bumpers about 4 or 6 times.
		numHits := 4
		if rand.Float32() > 0.5 {
			numHits = 6
		}

		type Point struct {
			X float64 `json:"x"`
			Y float64 `json:"y"`
		}

		// Generate path points.
		// Assume screen/table is normalized 0-100.
		path := make([]Point, numHits+1)
		for i := range numHits {
			// Random points near edges to simulate hitting bumpers
			edge := rand.Intn(4)
			var x, y float64
			switch edge {
			case 0: // Top
				x = rand.Float64() * 100
				y = 0
			case 1: // Right
				x = 100
				y = rand.Float64() * 100
			case 2: // Bottom
				x = rand.Float64() * 100
				y = 100
			case 3: // Left
				x = 0
				y = rand.Float64() * 100
			}
			path[i] = Point{X: x, Y: y}
		}
		// Final point is center-ish
		path[numHits] = Point{X: 50, Y: 50}

		return c.JSON(fiber.Map{
			"message": message,
			"path":    path,
		})
	})

	log.Fatal(app.Listen(":3000"))
}
